### ISSUE TITLE
[PE-D][Tester B] Phone number has too many digits

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S2-CS2103T-T17-1/tp#138]
It seems like there is no restriction about phone number digits. In reality, there should be a restriction about this, such as the Singapore phone number is eight digits.

![tomanydigitsforphone.png](https://raw.githubusercontent.com/QQH0828/ped/main/files/56320e90-173f-4268-8405-36a19f30e9e5.png)

-------------
Labels: `type.FunctionalityBug` `severity.Medium`
original: QQH0828/ped#10

**Comment by WillCWX** [comment]
Is this really necessary?

**Comment by ChickenChiang** [comment]
Will Implement feature constraint such that phone number can only have up to 15 digits, as that is the longest possible mobile phone number.

**Comment by ChickenChiang** [comment]
> Is this really necessary?

I think we could make the argument that since it is a phone number attribute and the maximum phone number lenght is 15 digits world-wide, it makes sense for an extremely long phone number to be a functionality bug. Will check if tutor/ prof Damith on forum

**Comment by ChickenChiang** [comment]
After reviewing the forum I think it is safe to say that this is a feature flaw, rather than a bug. 

# Suggested actions 
## Future features
Add the following to future features:
> Will Implement feature constraint such that phone number can only have up to 15 digits, as that is the longest possible mobile phone number.

## UG for add/edit command 
- Mention that phone numbers can be be infinitely long, which will be fixed in the future, and current users can use it as you see fit. 
## Possible Bug fix
- [ ] Additionally, since phone number is stored as an Integer throw exception if number given is greater than max int
